format = """
[](color_user)\
$username\
$hostname\
[](bg:color_dir fg:color_user)\
$directory\
[](fg:color_dir bg:color_git)\
$git_branch\
$git_status\
[](fg:color_git bg:color_lang)\
$nodejs\
$python\
$rust\
$golang\
$java\
$kotlin\
[](fg:color_lang bg:color_docker)\
$docker_context\
[](fg:color_docker bg:color_time)\
$time\
$cmd_duration\
[ ](fg:color_time)\
$line_break\
$character"""

add_newline = true

palette = "pastel"

[palettes.pastel]
color_user = "#9A348E"
color_dir = "#DA627D"
color_git = "#FCA17D"
color_lang = "#86BBD8"
color_docker = "#06969A"
color_time = "#33658A"

[username]
show_always = true
style_user = "bg:color_user fg:#FFFFFF bold"
style_root = "bg:color_user fg:#FF0000 bold"
format = '[ $user ]($style)'

[hostname]
ssh_only = false
style = "bg:color_user fg:#FFFFFF"
format = '[@$hostname ]($style)'

[directory]
style = "bg:color_dir fg:#FFFFFF"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_git fg:#1C1C1C"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:color_git fg:#1C1C1C"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = ""
style = "bg:color_lang fg:#1C1C1C"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:color_lang fg:#1C1C1C"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "🦀"
style = "bg:color_lang fg:#1C1C1C"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ""
style = "bg:color_lang fg:#1C1C1C"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ""
style = "bg:color_lang fg:#1C1C1C"
format = '[ $symbol ($version) ]($style)'

[kotlin]
symbol = ""
style = "bg:color_lang fg:#1C1C1C"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = ""
style = "bg:color_docker fg:#FFFFFF"
format = '[ $symbol $context ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_time fg:#FFFFFF"
format = '[  $time ]($style)'

[cmd_duration]
min_time = 500
style = "bg:color_time fg:#FFFFFF"
format = '[ 󱎫 $duration ]($style)'

[character]
success_symbol = "[❯](bold #9ece6a)"
error_symbol = "[❯](bold #f7768e)"
